-- SEQUENCE : 순차번호 생성기, 대부분 인위적인 PK사용 용도

DROP SEQUENCE FRIEND_SEQ;  --DDL 취소불가

CREATE SEQUENCE FRIEND_SEQ; --1부터 증가하고 한도가 없음 

CREATE SEQUENCE FRIEND_SEQ
    MAXVALUE 9999;

CREATE SEQUENCE FRIEND_SEQ
    MAXVALUE 9999
    NOCACHE -- 캐시 확보해놓지 않음 --NOCACHE 해놓지 않으면 일정량 확보해놓은 캐쉬 이후 부터 번호 부여  
    NOCYCLE; -- 새로 사이클 돌지않고 에러 출력 
    
CREATE SEQUENCE FRIEND_SEQ
    START WITH 1 -- 안써도 무방 
    INCREMENT BY 1 -- 안써도됨 
    MAXVALUE 9999
    MINVALUE 1
    NOCACHE
    NOCYCLE;    

SELECT FRIEND_SEQ.NEXTVAL FROM DUAL;
DROP TABLE FRIEND;
CREATE SEQUENCE FRIEND_SEQ
    MAXVALUE 9999
    NOCACHE
    NOCYCLE;

CREATE TABLE FRIEND(
    NUM NUMBER(4) PRIMARY KEY,  -- 시퀀스 이용 시퀀스의 자릿수와 맞춰야함
    NAME VARCHAR2(30) NOT NULL,
    TEL VARCHAR2(30) UNIQUE, -- NULL 허용, 유일한 값만 허용
    ADDRESS  VARCHAR2(300),
    LAST_MODIFYED DATE DEFAULT SYSDATE
);
INSERT INTO FRIEND(NUM, NAME, TEL, ADDRESS) 
    VALUES(FRIEND_SEQ.NEXTVAL, '홍길동', NULL, '서울시 용산구' );


INSERT INTO FRIEND(NUM, NAME, TEL, ADDRESS) 
    VALUES(FRIEND_SEQ.NEXTVAL, '박길동', '010-9999-9999', '서울시 강남구 강남대로94길 13 삼겸빌딩 402' );
    -- 에러가 실행됐어도 시퀀스 까지는 실행되어 있음 --시퀀스 구문 이후에 에러가 났기때문
    
INSERT INTO FRIEND(NUM, NAME, TEL, ADDRESS) 
    VALUES(FRIEND_SEQ.NEXTVAL, '신길동', '010-8888-88888', '서울시 영등포구' );
    -- 다음 시퀀스를 실행했을때 에러난 구문 이후 시퀀스 번호 부과됨 

SELECT * FROM FRIEND;

SELECT FRIEND_SEQ.CURRVAL FROM DUAL; -- 현재시퀀스 값
COMMIT;

--EX. 초기값 101부터 최대값 999,999까지 1씩 증가하는 TEST_SEQ 시퀀스를 생성 

CREATE SEQUENCE TEST_SEQ 
    START WITH 101 
    MAXVALUE 999999
    NOCACHE
    NOCYCLE;

SELECT TEST_SEQ.CURRVAL FROM DUAL; -- 시퀀스의 현재 값이 없어서 에러 




-- 연습문제 총연습문제 1

--MEMBER_LEVEL테이블 삭제
DROP TABLE MEMBER_LEVEL;

--MEMBER_LEVEL테이블 생성
CREATE TABLE MEMBER_LEVEL(
    LEVELNO NUMBER(10) PRIMARY KEY,
    LEVELNAME VARCHAR2(20) NOT NULL
);
--MEMBER_LEVEL테이블 생성확인
SELECT * FROM MEMBER_LEVEL; 

--MEMBER_LEVEL 칼럼 생성
INSERT INTO MEMBER_LEVEL VALUES(-1, 'BLACK');
INSERT INTO MEMBER_LEVEL VALUES(0, '일반');
INSERT INTO MEMBER_LEVEL VALUES(1, '실버');
INSERT INTO MEMBER_LEVEL VALUES(2, '골드');

--MEMBER테이블 삭제
DROP TABLE MEMBER;

--MEMBER테이블 생성
CREATE TABLE MEMBER(
    mNO NUMBER(4) PRIMARY KEY,
    mNAME VARCHAR2(20) NOT NULL,
    mPW VARCHAR2(8) CHECK(LENGTH(mPW) BETWEEN 1 AND 8) NOT NULL,
    mEMAIL VARCHAR2(50) UNIQUE,
    mPOINT NUMBER(10) CHECK(mPOINT >= 0),
    mRDATE DATE DEFAULT SYSDATE,
    LEVELNO NUMBER(10) REFERENCES MEMBER_LEVEL(LEVELNO)
);
--MEMBER테이블 확인
SELECT * FROM MEMBER;

-- MEMBER_MNO_SQ시퀀스 삭제
DROP SEQUENCE MEMBER_MNO_SQ;

-- MEMBER_MNO_SQ시퀀스 생성
CREATE SEQUENCE MEMBER_MNO_SQ
    START WITH 1    
    INCREMENT BY 1
    MAXVALUE 9999 -- nNO가 4자리
    MINVALUE 1
    NOCACHE
    NOCYCLE;

--MEMBER테이블 데이터 생성
INSERT INTO MEMBER 
    VALUES(MEMBER_MNO_SQ.NEXTVAL, '홍길동', 'AA', 'hong@hong.com', 0, TO_DATE('22/03/10','RR/MM/DD'), 0); 
INSERT INTO MEMBER(mNO, mNAME, mPW, mEMAIL, mPOINT, LEVELNO) 
    VALUES(MEMBER_MNO_SQ.NEXTVAL, '신길동', 'BB', 'sin@sin.com', 1000 , 1);

--출력
SELECT mNO, mNAME, mRDATE, mEMAIL, mPOINT "point", CONCAT(LEVELNAME, '고객') "LEVELNAME"
    FROM MEMBER M , MEMBER_LEVEL ML
    WHERE M.LEVELNO = ML.LEVELNO;







