-- 쇼핑몰 설계

--MEMBER 
    --ID(PK) mNAME ADDR TEL EMAIL 
--PRODUCT 
    -- CODE(PK) pNAME PRICE STOCK
--ORDERS
    --ORDERNO, ORDERDATE, ORDERADD ORDERTEL, MID, PCODE 
--장바구니????????????????
    --MID  pCODE QYT COST
   --------------장바구니에 있는 정보가 주문 상세로---------------------------
--주문상세 
    -- 주문번호(oNO pCODE, QTYM COST
    
    
--1. 요구사항을 보고 테이블 설계
--2. SQL문 (테이블 생성, 시퀀스 생성, 데이터 INSERT 및 재고 UPDATE)


--MEMBER 테이블 생성
DROP TABLE MEMBER;
CREATE TABLE MEMBER(
    mID VARCHAR2(30) PRIMARY KEY,
    mNAME VARCHAR2(10) NOT NULL,
    mADDRE VARCHAR2(50) ,
    mTEL VARCHAR2(20) NOT NULL UNIQUE);

--MEMBER 필드 입력
INSERT INTO MEMBER VALUES('abc', '홍길동', '서울 강남구', '010-1111-1111');
INSERT INTO MEMBER VALUES('def', '전투왕', '서울 서대문구', '010-2222-2222');
SELECT * FROM MEMBER;

--PRODUCT 테이블 생성
DROP TABLE PRODUCT;
CREATE TABLE PRODUCT(
    pCODE VARCHAR2(10) PRIMARY KEY,
    pNAME VARCHAR2(30),
    pPRICE NUMBER(10) NOT NULL,
    pQTY NUMBER(10) NOT NULL
    );

--PRODUCT 필드 입력
INSERT INTO PRODUCT VALUES('A1', '맥주', '3000', '100');
INSERT INTO PRODUCT VALUES('A2', '소주', '2000', '100');
INSERT INTO PRODUCT VALUES('B1', '땅콩', '3500', '100');
INSERT INTO PRODUCT VALUES('B2', '오징어', '5000', '100');
INSERT INTO PRODUCT VALUES('C1', '기저귀', '7000', '100');
SELECT * FROM PRODUCT;

--CART 테이블
DROP TABLE CART;
CREATE TABLE CART(
    cNO NUMBER(10) PRIMARY KEY,
    mID VARCHAR2(30) REFERENCES MEMBER(mID) NOT NULL,
    pCODE VARCHAR2(10) REFERENCES PRODUCT(pCODE) NOT NULL,
    cQTY NUMBER(10) NOT NULL,
    cCOST NUMBER(10)  
    );
SELECT * FROM CART;
--CART 데이터 입력
CREATE SEQUENCE CART_SQ
    MAXVALUE 9999
    NOCACHE;
    
INSERT INTO CART 
    VALUES(CART_SQ.NEXTVAL,'abc','A1',2,(SELECT pPRICE *2 FROM PRODUCT WHERE pCODE = 'A1')); 

SELECT * FROM CART;


--ORDERS 테이블 생성
DROP TABLE ORDERS;
CREATE TABLE ORDERS(
    oNO VARCHAR2(20) PRIMARY KEY,
    mID VARCHAR2(30) REFERENCES MEMBER(mID) NOT NULL,
    oDATE DATE DEFAULT SYSDATE,
    oADDRE VARCHAR2(10) NOT NULL,
    oTEL VARCHAR2(20) NOT NULL
);

SELECT * FROM ORDERS;

--ORDERS 필드 입력
DROP SEQUENCE ORDER_SQ;
CREATE SEQUENCE ORDER_SQ
    MAXVALUE 99999
    NOCACHE;

INSERT INTO ORDERS VALUES (TO_CHAR(SYSDATE, 'YYMMDD') ||TRIM(TO_CHAR(ORDER_SQ.nextval, '0009')), 'abc', SYSDATE, '서울시 영등포', '010-1111-1111');  
INSERT INTO ORDERS VALUES (TO_CHAR(SYSDATE, 'YYMMDD') ||TRIM(TO_CHAR(ORDER_SQ.nextval, '0009')), SYSDATE, 'def', 'A2', 1000);  

DELETE FROM ORDERS 
    WHERE oNO = '220419 0001';
SELECT * FROM ORDERS;




    



















