-- VIEW, INLINE VIEW,  TOP-N  구문
-- 1. VEIW : 가상의 테이블  (1) 단순뷰 (2) 복합뷰 

-- (1) 단순뷰 : 하나의 테이블로 구성한 뷰  - 가상의 테이블

-- EMPv0이라는 VIEW 생성 또는 수정 = EMP테이블 일부 필드를 갖는 가상의 테이블 
-- 뷰만들면 데이터사전 수정됨?
SELECT * FROM USER_VIEWS; -- 데이터 딕셔너리 뷰 확인
CREATE OR REPLACE VIEW EMPv0
    AS SELECT EMPNO, ENAME, JOB, MGR, HIREDATE, DEPTNO FROM EMP; -- DDL을 수행하면 데이터 딕셔너리 자동 수정 

SELECT * FROM EMPv0; -- 데이터를 제한해서 원하는 부분만 결과 줌 
-- 가상의 테이블 
INSERT INTO EMPv0 VALUES (1111, '홍', 'ITMANAGER', '7369', SYSDATE, 40); -- 뷰에 INSERT하면 EMP테이블에도 INSERT 
SELECT * FROM EMPv0;
SELECT * FROM EMP; -- 뷰에 데이터 넣으면 실제 테이블에도 데이터 들어감

UPDATE EMPv0 SET JOB = 'MANAGER' WHERE EMPNO = 1111; --  뷰 UPDATE하면 EMP테이블도 UPDATE 
SELECT * FROM EMPv0;
SELECT * FROM EMP;

DELETE FROM EMPv0 WHERE EMPNO = 1111; -- 뷰 DELETE 하면 EMP테이블도 DELETE
SELECT * FROM EMPv0;
SELECT * FROM EMP;




-- EMPv0이라는 VIEW : EMP테이블에 30번 부서만 
CREATE OR REPLACE VIEW EMPv0 
    AS SELECT * FROM EMP WHERE DEPTNO =30;

DESC EMPv0;

SELECT * FROM EMPv0;

INSERT INTO EMPv0 VALUES (1111, '홍', NULL,NULL,SYSDATE,9000, 900, 30); --30번 부서 INSERT 

SELECT * FROM EMP; --실제 테이블에도 INSERT


-- 40번 부서 입력은 가능 
INSERT INTO EMPv0 VALUES(1112, '박', NULL,NULL,SYSDATE, 8000,800,40); --다른 부서 데이터를 입력이 가능하나 해당 뷰에 제약에 따라 볼수는 없다
SELECT * FROM EMPv0; --30번 부서만 출력하는 기준 이 있기때문에 볼수없음 

DELETE FROM EMPv0 WHERE EMPNO IN (1111,1112); --30 번 부서만 있다고 생각함? 기준에 

DELETE FROM EMP WHERE EMPNO = 1112; --40번 부서는 EMP에서 삭제


-- EMPv0 뷰 생성 : ENAME, JOB, GHIREDATE 만으로 뷰 
CREATE OR REPLACE VIEW EMPv0
    AS SELECT ENAME, JOB, HIREDATE FROM EMP;
    
INSERT INTO EMPv0 VALUES('홍', 'SALESMAN', SYSDATE);
-- 뷰 만들때 인서트 가능게 하려면 
COMMIT; 



-- VIEW의 제한조건 (1) 뷰의 조건 (2) 읽기 전용 
-- WITH CHECK OPTION 을 설정한 뷰는 뷰의 조건에 해당되는 데이터만 삽입, 수정, 삭제 가능
-- WITH READ ONLY를 설정한 뷰는 읽기 전용 뷰 

-- EMPv0 : EMP 테이블에서 30번 부서만 
CREATE OR REPLACE VIEW EMPv0
    AS SELECT * FROM EMP WHERE DEPTNO = 30
    WITH CHECK OPTION; --해당 조건에 만족되는 항목만 DML가능
    
INSERT INTO EMPv0 VALUES(1111, '홍', NULL, NULL, SYSDATE, 9000, 900, 30); -- 30번 부서만 INSERT
INSERT INTO EMPv0 VALUES(1112, '홍', NULL, NULL, SYSDATE, 9000, 900, 40); -- WHERE 조건에 만족하지 않으면 불가
SELECT * FROM EMP;
SELECT * FROM EMPv0;
DELETE FROM EMPv0 WHERE ENAME = 'SMITH'; -- 20번 부서 SMITH
DELETE FROM EMPv0 WHERE EMPNO = 1111; --30번 부서 DELETE

-- EMPv0 : 읽기 전용 뷰 
CREATE OR REPLACE VIEW EMPv0
    AS SELECT EMPNO, ENAME, JOB, MGR, DEPTNO FROM EMP
    WITH READ ONLY;
INSERT INTO EMPv0 VALUES (1111, '홍', NULL, NULL, 40); -- 에러(읽기전용 뷰)
SELECT * FROM EMPv0;

-- (2) 복합뷰 : 2개 이상의 테이블로 구성한 뷰이거나 가상의 필드로 뷰를 만들경우. DML문을 제한적으로 사용 

-- 1. 2개 이상의 테이블로 뷰 생성
CREATE OR REPLACE VIEW EMPv0
    AS SELECT EMPNO, ENAME, JOB, DNAME, LOC
    FROM EMP E, DEPT D 
    WHERE E.DEPTNO = D.DEPTNO;
    
SELECT * FROM EMPv0;

INSERT INTO EMPv0 VALUES(1111, 'HONG', 'MANAGER', 'RESERCH', 'DALLAS'); -- 복합뷰는 갱신불가

--2. 가상의 필드로 뷰를 생성 -- 연산자나 함수가들어가는 가상의필드
    -- 컬럼에 별칭(영문자로 시작, 숫자, _ , 30자이내로 )을 이용하여 뷰를 생성해야한다. 
CREATE OR REPLACE VIEW EMPv0
    AS SELECT EMPNO, ENAME, SAL *12 FROM EMP WHERE DEPTNO = 10; -- SAL*12라는 필드는 없어서 에러 
CREATE OR REPLACE VIEW EMPv0
    AS SELECT EMPNO, ENAME, SAL *12 "YEAR" FROM EMP WHERE DEPTNO = 10; -- 별칭으로 생성 
    
SELECT * FROM EMPv0;

CREATE OR REPLACE VIEW EMPv0
    AS SELECT EMPNO, ENAME, ROUND(SAL, -2) FROM EMP WHERE DEPTNO = 10; -- 에러 
CREATE OR REPLACE VIEW EMPv0(EMPNO, ENAME, YEAR_SAL)    -- 별칭들만 따로 나열  -- 모든 필드를 명시해 구분해줘야함 
    AS SELECT EMPNO, ENAME, ROUND(SAL, -2) FROM EMP WHERE DEPTNO = 10;

INSERT INTO EMPv0 VALUES(1111, '홍', 2400); -- 복합뷰는 갱신불가 

-- EX. 부서번호, 최소급여, 최대급여, 부서평균 급여를 포함한 DEPTv1 뷰를 생성
CREATE OR REPLACE VIEW DEPTv1
    AS SELECT DEPTNO, MIN(SAL) "MINSAL", MAX(SAL) "MAXSAL" , TRUNC(AVG(SAL)) "AVGSAL"
        FROM EMP 
        GROUP BY DEPTNO;
SELECT * FROM DEPTv1;

-- EX. 직책 부서를 포함한 EMPv0뷰를 생성 : DISTINCT를 포함한 뷰는 읽기 전용
CREATE OR REPLACE VIEW EMPv0
    AS SELECT DISTINCT JOB, DEPTNO FROM EMP ORDER BY DEPTNO;

SELECT * FROM EMPv0;

INSERT INTO EMPv0 VALUES ('CLERK', 10); -- 읽기 전용이라 에러 





-- 2. INLINE VIEW : FROM 절 상의 서브쿼리를 INLINE VIEW라 하며, FROM 절에 오는 서브쿼리는 VIEW처럼 작용 

--EX. 급여가 2000을 초과하는 사원의 평균 급여
SELECT AVG(SAL) FROM EMP WHERE SAL>2000;

SELECT AVG(SAL) FROM (SELECT SAL FROM EMP WHERE SAL>2000);

--EX. 부서 평균 월급보다 높은 사원을 사번, 이름, 급여(서브쿼리 연습문제 24,25)
SELECT EMPNO, ENAME, SAL 
    FROM EMP E
    WHERE SAL > (SELECT AVG(SAL) FROM EMP WHERE DEPTNO= E.DEPTNO); 
SELECT EMPNO, ENAME, AVGSAL
    FROM EMP E, (SELECT DEPTNO, AVG(SAL) "AVGSAL" FROM EMP GROUP BY DEPTNO) A
    WHERE E.DEPTNO = A.DEPTNO AND SAL > AVGSAL; -- INLINE VIEW



--3. TOP-N 구문(TOP 1~10등 / TOP 11~20등 / TOP 6~10등)

-- ROWNUM : FROM의 테이블로부터 가져온 순서 
SELECT ROWNUM, ENAME FROM EMP WHERE DEPTNO = 20; 
SELECT ROWNUM, ENAME FROM EMP WHERE DEPTNO = 20 ORDER BY ENAME;
-- 등수, 이름, SAL(전체행에 대해)
SELECT ROWNUM, ENAME, SAL FROM EMP ORDER BY SAL DESC; -- ROWNUM이 등수가 아니고 테이블로 부터 가져온 순서 
SELECT ROWNUM, ENAME, SAL FROM (SELECT * FROM EMP ORDER BY SAL DESC); --등수 출력용으로 권장
-- INLIN 뷰로 먼저 정렬된것을 ROWNUM으로 번호매겨서 등수로 나옴

--함수를 이용한 RANK출력 (권장하지않음)
SELECT RANK() OVER(ORDER BY SAL DESC) RANK,
    DENSE_RANK() OVER(ORDER BY SAL DESC) DENSE_RANK,
    ROW_NUMBER() OVER(ORDER BY SAL DESC) ROW_NUMBER,
    ENAME, SAL FROM EMP;

-- SAL 기준으로 1~5 등 
SELECT ROWNUM, ENAME, SAL FROM (SELECT ENAME, SAL FROM EMP ORDER BY SAL DESC)
    WHERE ROWNUM <= 5;
-- SAL 기준으로 6~10 
SELECT ROWNUM, ENAME, SAL FROM (SELECT ENAME, SAL FROM EMP ORDER BY SAL DESC)
    WHERE ROWNUM BETWEEN 6 AND 10; -- 결과가 나오지 않는다.
SELECT ENAME, SAL 
FROM (SELECT ROWNUM, ENAME, SAL FROM (SELECT ENAME, SAL FROM EMP ORDER BY SAL DESC))
;
-- TOP - N 구문 1단계
SELECT ROWNUM RN, ENAME, SAL FROM (SELECT ENAME, SAL FROM EMP ORDER BY SAL DESC);
-- TOP - N 구문 2단계 (완성된 TOP-N 구문)
SELECT ROWNUM, RN, ENAME, SAL 
    FROM (SELECT ROWNUM RN, ENAME, SAL FROM (SELECT ENAME, SAL FROM EMP ORDER BY SAL DESC)) A
    WHERE RN BETWEEN 6 AND 10; --인라인뷰 구문에 ROWNUM에 별칭을 주어서 구분해줘야함


--이름을 알파벳 순서대로 정렬해서 6~10번째 까지 출력(등수, 이름, 사번, JOB, MGR, HIREDATE)
SELECT RN, ENAME, EMPNO, JOB, MGR, HIREDATE
    FROM(SELECT ROWNUM RN, ENAME, EMPNO, JOB, MGR, HIREDATE FROM(SELECT * FROM EMP ORDER BY ENAME))
    WHERE RN BETWEEN 6 AND 10;
    
    
    
    
    
    
-- 1. 부서명과 사원명을 출력하는 용도의 뷰, DNAME_ENAME_VU 를 작성하시오
CREATE OR REPLACE VIEW DNAME_ENAME_VU
    AS SELECT DNAME, ENAME FROM EMP E, DEPT D WHERE E.DEPTNO=D.DEPTNO;
    
SELECT * FROM DNAME_ENAME_VU;

-- 2. 사원명과 직속상관명을 출력하는 용도의 뷰,  WORKER_MANAGER_VU를 작성하시오
CREATE OR REPLACE VIEW WORKER_MANAGER_VU
    AS SELECT E1.ENAME "사원", E2.ENAME "직속상관" FROM EMP E1, EMP E2 WHERE E1.MGR = E2.EMPNO
    WITH READ ONLY; -- 필드 이름을 같게할수없다. 별칭 반드시

SELECT * FROM WORKER_MANAGER_VU;

-- 3. 부서별 급여합계 등수를 출력하시오(부서번호, 급여합계, 등수). 
SELECT DEPTNO, SUMSAL, ROWNUM
    FROM(SELECT DEPTNO, SUM(SAL) "SUMSAL" FROM EMP GROUP BY DEPTNO ORDER BY SUMSAL DESC);   

-- 3-1. 부서별 급여합계 등수가 2~3등인 부서번호, 급여합계, 등수를 출력하시오. -- 학생 질문
SELECT DEPTNO, SUMSAL, RN 
    FROM (SELECT DEPTNO, SUMSAL, ROWNUM "RN"
                FROM(SELECT DEPTNO, SUM(SAL) "SUMSAL" FROM EMP GROUP BY DEPTNO ORDER BY SUMSAL DESC))
    WHERE RN BETWEEN 2 AND 3;
    
-- 4. 사원테이블에서 사번, 사원명, 입사일을 입사일이 최신에서 오래된 사원 순으로 정렬하시오
SELECT * FROM EMP ORDER BY HIREDATE DESC;
SELECT EMPNO, ENAME, HIREDATE FROM EMP ORDER BY HIREDATE DESC;

-- 5. 사원테이블에서 사번, 사원명, 입사일을 입사일이 최신에서 오래된 사원 5명을 출력하시오
SELECT RN, EMPNO, ENAME, HIREDATE
FROM ( SELECT ROWNUM "RN", EMPNO, ENAME, HIREDATE 
            FROM (SELECT EMPNO, ENAME, HIREDATE FROM EMP ORDER BY HIREDATE DESC))
WHERE RN BETWEEN 1 AND 5;
        
SELECT * 
    FROM (SELECT EMPNO, ENAME, HIREDATE FROM EMP ORDER BY HIREDATE DESC) A
    WHERE ROWNUM BETWEEN 1 AND 5;

-- 6. 사원 테이블에서 사번, 사원명, 입사일을 최신부터 오래된 순으로 6번째로 늦은 사원부터 10번째 사원까지 출력
SELECT RN, EMPNO, ENAME, HIREDATE
FROM ( SELECT ROWNUM "RN", EMPNO, ENAME, HIREDATE 
            FROM (SELECT EMPNO, ENAME, HIREDATE FROM EMP ORDER BY HIREDATE DESC))
WHERE RN BETWEEN 6 AND 10;



















