-- TRANSACTION 명령어 : COMMIT;(트랜잭션 반영) ROLLBACK;(트랜잭션 취소) SAVEPOINT;(트랜잭션 분할);

DROP TABLE DEPT01;

SELECT * FROM DEPT01;

CREATE TABLE DEPT01 AS SELECT * FROM DEPT; -- DDL 이라 트랜잭션에 안쌓이고 바로 반영
SELECT * FROM DEPT01; -- SELECT문도 트랜잭션에 반영되지않는다.

DELETE FROM DEPT01; -- 트랜잭션에 쌓여있다. 
SELECT * FROM DEPT01; 

ROLLBACK; -- 트랜잭션에 있는 작업 취소 , 새로운 트랜잭션 시작 
SELECT * FROM DEPT01; 

DELETE FROM DEPT01 WHERE DEPTNO = 40;
COMMIT; -- 트랜잭션 작업 수행 -- 새로운 트랜잭션 시작 
SELECT * FROM DEPT01; 

DELETE FROM DEPT01 WHERE DEPTNO = 30;
SELECT * FROM DEPT01; 
SAVEPOINT C1; -- C1지점: 10, 20번 부서  SAVEPOINT 생성 실행해야함

DELETE FROM DEPT01 WHERE DEPTNO = 20;
SELECT * FROM DEPT01; 
SAVEPOINT C2; -- C2 지점 - 10번 부서 SAVEPOINT 생성

DELETE FROM DEPT01 WHERE DEPTNO = 10;
SELECT * FROM DEPT01; -- 데이터 없음

ROLLBACK TO C2;
SELECT * FROM DEPT01;

ROLLBACK TO C1;
SELECT * FROM DEPT01;
COMMIT;
SELECT * FROM DEPT01;























