DROP TABLE CUSTOMER;

CREATE TABLE CUSTOMER(
    CNO NUMBER(3),
    CPHONE VARCHAR2(20) UNIQUE,
    CNAME VARCHAR2(15) NOT NULL,
    CPOINT NUMBER(9) DEFAULT 1000,
    PRIMARY KEY(CNO)
);
DROP SEQUENCE CUSTOMER_SQ;

CREATE SEQUENCE CUSTOMER_SQ
    NOCACHE
    NOCYCLE
    MAXVALUE 999;

INSERT INTO CUSTOMER VALUES(CUSTOMER_SQ.NEXTVAL, '010-9999-9999', '홍길동', 2000);
INSERT INTO CUSTOMER(CNO, CPHONE, CNAME) VALUES(CUSTOMER_SQ.NEXTVAL, '010-8888-8888', '홍길동');
INSERT INTO CUSTOMER(CNO, CPHONE, CNAME) VALUES(CUSTOMER_SQ.NEXTVAL, '010-7777-8888', '김길동');

SELECT * FROM CUSTOMER;

-- 가입 int
INSERT INTO CUSTOMER(CNO, CPHONE, CNAME, CPOINT) VALUES(CUSTOMER_SQ.NEXTVAL, '010-7777-8888', '김길동', 1000);
-- 연락처 조회  ArrayList 
SELECT CNO, CPHONE, CNAME, CPOINT FROM CUSTOMER WHERE CPHONE LIKE '%'||'8888';
-- 출력 모든 회원정보 ArrayList 
SELECT CNO, CPHONE, CNAME, CPOINT FROM CUSTOMER;

COMMIT;
