DROP TABLE FRIEND;

DROP SEQUENCE FRIEND_SQ;

CREATE SEQUENCE FRIEND_SQ
    NOCACHE
    NOCYCLE
    MAXVALUE 100;
    

CREATE TABLE FRIEND(
    FNO NUMBER(2) PRIMARY KEY,
    FNAME VARCHAR(20) NOT NULL,
    FTEL VARCHAR(20) NOT NULL UNIQUE
);

INSERT INTO FRIEND(FNO, FNAME, FTEL) VALUES(FRIEND_SQ.NEXTVAL, '홍길동', '010-4444-4444');  

-- 친구 추가
-- public int friendsUpdate(String fname, String ftel)
INSERT INTO FRIEND(FNO, FNAME, FTEL) VALUES(FRIEND_SQ.NEXTVAL, '장길동', '010-2345-6455');  
INSERT INTO FRIEND(FNO, FNAME, FTEL) VALUES(FRIEND_SQ.NEXTVAL, '윤길동', '010-4652-1154');  
INSERT INTO FRIEND(FNO, FNAME, FTEL) VALUES(FRIEND_SQ.NEXTVAL, '장준길', '010-6655-1548');  
INSERT INTO FRIEND(FNO, FNAME, FTEL) VALUES(FRIEND_SQ.NEXTVAL, '홍길수', '010-0258-8849');  

-- 친구 검색
-- 이름검색?
-- public Friends searchFriends(String fname)
SELECT * FROM FRIEND WHERE FNAME LIKE '%%' ;
SELECT * FROM FRIEND;


-- 연락처검색?
-- public Friends searchFriends(String fname)
SELECT * FROM FRIEND WHERE FTEL LIKE '%2345%' ;

SELECT * FROM FRIEND;
commit;

