--5PAGE 
-- MAJOR 삭제 및 생성
DROP TABLE MAJOR;

CREATE TABLE MAJOR(
    MAJOR_CODE NUMBER(1) PRIMARY KEY,
    MAJOR_NAME VARCHAR2(30) UNIQUE,
    MAJOR_OFFICE_LOC VARCHAR2(30) NOT NULL
);
SELECT * FROM MAJOR;

-- MAJOR 데이터 생성
INSERT INTO MAJOR VALUES( 1, '경영정보', '경영관 305호');
INSERT INTO MAJOR VALUES( 2, '소프트웨어 공학', '정보관 808호');
INSERT INTO MAJOR VALUES( 3, '디자인', '예술관 606호');
INSERT INTO MAJOR VALUES( 4, '경제', '경상관 202호');

-- STUDENT 삭제 및 생성
DROP TABLE STUDENT; 

CREATE TABLE STUDENT(
    STUDENT_CODE VARCHAR2(10),
    STUDENT_NAME VARCHAR2(20),
    SCORE NUMBER(3) CHECK(SCORE BETWEEN 0 AND 100),
    MAJOR_CODE NUMBER(1) REFERENCES MAJOR(MAJOR_CODE)
);

SELECT * FROM STUDENT;

-- STUDENT 데이터 생성
INSERT INTO STUDENT VALUES('A01', '김길동', 100, 1);
INSERT INTO STUDENT VALUES('A02', '문길동', 90, 2);
INSERT INTO STUDENT VALUES('A03', '홍길동', 95, 1);