--4 PAGE
-- BOOKCATEGORY 삭제 및 생성
DROP TABLE BOOKCATEGORY; 

CREATE TABLE BOOKCATEGORY(
    CATEGORY_CODE NUMBER(3) PRIMARY KEY,
    CATEGORY_NAME VARCHAR2(50) UNIQUE,
    OFFICE_LOC VARCHAR2(50) NOT NULL
);
SELECT * FROM BOOKCATEGORY;

-- BOOK 삭제 및 생성
DROP TABLE BOOK; 

CREATE TABLE BOOK(
    CATEGORY_CODE NUMBER(3) REFERENCES BOOKCATEGORY(CATEGORY_CODE),
    BOOKNO VARCHAR2(20) NOT NULL,
    BOOKNAME VARCHAR2(50),
    PUBLISHER VARCHAR2(50),
    PUBYEAR NUMBER(4) DEFAULT EXTRACT(YEAR FROM SYSDATE) 
);
SELECT * FROM BOOK;

-- BOOKCATEGORY 데이터 생성
INSERT INTO BOOKCATEGORY VALUES (100, '철학', '3층 인문실');
INSERT INTO BOOKCATEGORY VALUES (200, '인문', '3층 인문실');
INSERT INTO BOOKCATEGORY VALUES (300, '자연과학', '4층 과학실');
INSERT INTO BOOKCATEGORY VALUES (400, 'IT', '4층 과학실');

-- BOOK 데이터 생성
INSERT INTO BOOK(CATEGORY_CODE, BOOKNO, BOOKNAME, PUBLISHER) 
    VALUES(100, '100A01', '철학자의 삶', '더존출판' );
INSERT INTO BOOK
    VALUES(400, '400A01', '이것이 DB다', '더존출판', 2018 );
    