DROP TABLE MVC2MEMBER;

CREATE TABLE MVC2MEMBER(
    MID VARCHAR2(30) PRIMARY KEY,
    MPW VARCHAR2(30) NOT NULL,
    MNAME VARCHAR2(30) NOT NULL,
    MEMAIL VARCHAR2(30) UNIQUE NOT NULL,
    MPHOTO VARCHAR2(30) NOT NULL,
    MBIRTH DATE, 
    MADDRESS VARCHAR2(300),
    MRDATE DATE DEFAULT SYSDATE
);

-- 회원가입시 ID중복체크 
SELECT * FROM MVC2MEMBER WHERE MID = 'BBB';

-- 회원가입시 EMAIL중복체크
SELECT * FROM MVC2MEMBER WHERE MEMAIL = 'EE@EE.COM';

-- 회원가입
INSERT INTO MVC2MEMBER(MID, MPW, MNAME, MEMAIL, MPHOTO, MBIRTH, MADDRESS) 
    VALUES('BBB', '111', '홍길동', 'EE@EE.COM', 'NOTHING.JPG', TO_DATE('1991-11-04', 'YYYY/MM/DD'), '서울시' );
                                               
commit;
    