DROP TABLE MEMBER;

CREATE TABLE MEMBER(
    ID VARCHAR2(30) PRIMARY KEY,
    PW VARCHAR2(30) NOT NULL,
    NAME VARCHAR2(30) NOT NULL,
    BIRTH DATE,
    RDATE DATE DEFAULT SYSDATE NOT NULL
);

-- 회원가입 
INSERT INTO MEMBER (ID, PW, NAME, BIRTH)
    VALUES('AAA', '1', '홍길동', '1998-12-12');
INSERT INTO MEMBER (ID, PW, NAME, BIRTH)
    VALUES('BBB', '1', '홍길동', '1998-12-12');
INSERT INTO MEMBER (ID, PW, NAME, BIRTH)
    VALUES('CCC', '1', '홍길동', '1998-12-12');
-- to_date('1998-12-12', 'yyyy-mm-dd')
-- 회원리스트
SELECT * FROM MEMBER;

commit;