DROP TABLE BOOK;

DROP SEQUENCE BOOK_SEQ;

CREATE SEQUENCE BOOK_SEQ
    MAXVALUE 99999
    NOCACHE
    NOCYCLE;

CREATE TABLE BOOK(
    BID NUMBER(5) PRIMARY KEY, -- 책번호
    BTITLE VARCHAR2(100) NOT NULL, -- 책제목
    BPRICE NUMBER(7) NOT NULL,
    BIMAGE1 VARCHAR2(30) NOT NULL, -- 책 대표 이미지(첨부 안할 경우: noImg.png) 
    BIMAGE2 VARCHAR2(30) NOT NULL, -- 책 부가 이미지(첨부 안할경우 : NOTHING.JPG)
    BCONTENT VARCHAR2(4000), -- 책 설명(한글 1,333글자 이내) 이상일경우 LCOB 
    BDISCOUNT NUMBER(3) NOT NULL,
    BRDATE DATE DEFAULT SYSDATE -- 등록일
);   
-- BIMAGE BLOB -- 파일들어가는 자료형?

SELECT * FROM BOOK;

-- 책 등록
INSERT INTO BOOK(BID, BTITLE, BPRICE, BIMAGE1, BIMAGE2, BCONTENT, BDISCOUNT) 
    VALUES(BOOK_SEQ.NEXTVAL, '이것은 자바다', 30000, 'noImg.png', 'NOTHING.jpg', '책설명', 20);

INSERT INTO BOOK(BID, BTITLE, BPRICE, BIMAGE1, BIMAGE2, BCONTENT, BDISCOUNT) 
    VALUES(BOOK_SEQ.NEXTVAL, 'JSP도서', 23000, 'noImg.png', 'NOTHING.jpg', '책설명', 10);

INSERT INTO BOOK(BID, BTITLE, BPRICE, BIMAGE1, BIMAGE2, BCONTENT, BDISCOUNT) 
    VALUES(BOOK_SEQ.NEXTVAL, 'Spring', 30000, 'noImg.png', 'NOTHING.jpg', '책설명', 5);

INSERT INTO BOOK(BID, BTITLE, BPRICE, BIMAGE1, BIMAGE2, BCONTENT, BDISCOUNT) 
    VALUES(BOOK_SEQ.NEXTVAL, '봄', 40000, 'noImg.png', 'NOTHING.jpg', '책설명', 20);

-- 책 목록(전체LIST)
SELECT * FROM BOOK ORDER BY BRDATE DESC;
DELETE from book where bid = 10; 
-- 책 목록(TOP-N구문)
SELECT * 
    FROM (SELECT ROWNUM RN, B.*
                FROM (SELECT * FROM BOOK ORDER BY BRDATE DESC) B)
                    WHERE RN BETWEEN 2 AND 3;
                    
-- 등록된 책 갯수
SELECT COUNT(*) CNT FROM BOOK;

-- 책 상세보기(BID로 DTO 가져오기)
SELECT * FROM BOOK WHERE BID = 1;

COMMIT;













