-- 테이블 생성, 시퀀스
DROP TABLE JOB;

CREATE TABLE JOB(
    JNO NUMBER(2) PRIMARY KEY,
    JNAME VARCHAR2(20) NOT NULL
);

SELECT * FROM JOB;

DROP TABLE PERSON;

CREATE TABLE PERSON(
    PNO NUMBER(2) PRIMARY KEY,
    PNAME VARCHAR2(20) NOT NULL,
    KOR NUMBER(3),
    ENG NUMBER(3),
    MAT NUMBER(3),
    JNO NUMBER(2) REFERENCES JOB(JNO) NOT NULL
);

SELECT * FROM PERSON;

DROP SEQUENCE PERSON_NO_SQ;

DELETE FROM PERSON 

CREATE SEQUENCE PERSON_NO_SQ
    NOCACHE
    NOCYCLE
    MAXVALUE 99;
-- 더미데이터 
INSERT INTO JOB VALUES(10, '배우');
INSERT INTO JOB VALUES(20, '가수');

INSERT INTO PERSON VALUES(PERSON_NO_SQ.NEXTVAL, '정우성', 90, 80,81,10 );
INSERT INTO PERSON VALUES(PERSON_NO_SQ.NEXTVAL, '박세영', 80, 90,80,10 );
INSERT INTO PERSON VALUES(PERSON_NO_SQ.NEXTVAL, '배수지', 20, 90,90,20 );
INSERT INTO PERSON VALUES(PERSON_NO_SQ.NEXTVAL, '설현', 95, 95,95,20 );
INSERT INTO PERSON VALUES(PERSON_NO_SQ.NEXTVAL, '송혜교', 100, 100,100,10 );

COMMIT;
-- 1.번 : PNAME, JNAME, KOR, ENG, MAT 를 입력받아 INSERT 
INSERT INTO PERSON 
    VALUES(PERSON_NO_SQ.NEXTVAL, '정우성', 90, 80,81,(SELECT JNO FROM JOB WHERE JNAME = '배우') );

-- 2번 : 직업명을 입력받아 등수, 이름(PNO), 직업명, 국어, 영어, 수학, 총점을 출력(총점 기준으로 내림차순 정렬)
SELECT ROWNUM "등수", PNO, PNAME, JNAME, KOR, ENG, MAT, TOT
    FROM( SELECT PNO, PNAME, JNAME, KOR, ENG, MAT, (KOR+ENG+MAT) "TOT"
                FROM PERSON P, JOB J WHERE P.JNO=J.JNO ORDER BY TOT DESC);

SELECT ROWNUM "등수",PNAME, JNAME, KOR, ENG, MAT, TOT
    FROM( SELECT PNO, PNAME||'('||PNO||'번)' PNAME , JNAME, KOR, ENG, MAT, (KOR+ENG+MAT) "TOT"
                FROM PERSON P, JOB J WHERE P.JNO=J.JNO AND JNAME = '배우' ORDER BY TOT DESC);

-- 3번 : 모든 행의 등수  이름(PNO), 직업명, 국어, 영어, 수학, 총점을 출력(총점 기준으로 내림차순 정렬)

SELECT ROWNUM "등수", PNO, PNAME, JNAME, KOR, ENG, MAT, TOT
    FROM( SELECT PNO, PNAME, JNAME, KOR, ENG, MAT, (KOR+ENG+MAT) "TOT"
                FROM PERSON P, JOB J WHERE P.JNO=J.JNO ORDER BY TOT DESC);










