DROP TABLE CUSTOMER;

CREATE TABLE CUSTOMER(
    CID VARCHAR2(50) NOT NULL,
    CPW VARCHAR2(50) NOT NULL,
    CNAME VARCHAR2(50) NOT NULL,
    CTEL VARCHAR2(50) NOT NULL,
    CEMAIL VARCHAR2(50),
    CADDRESS VARCHAR2(250),
    CGENDER VARCHAR2(10) NOT NULL,
    CBIRTH DATE NOT NULL,
    CRDATE DATE DEFAULT SYSDATE NOT NULL
);

-- 정보 가져오기
SELECT * FROM CUSTOMER WHERE CID = 'AAA';

-- 회원 가입
INSERT INTO CUSTOMER(CID, CPW, CNAME, CTEL, CEMAIL, CADDRESS, CGENDER, CBIRTH, CRDATE)
    VALUES('AAA', '111', '홍길동', '010-3333-3333', 'HONG@HONG.COM', '서울시', 'M', '1991-11-04', SYSDATE);

-- 정보 수정
UPDATE CUSTOMER SET
    CPW = '112',
    CNAME = '김길동',
    CTEL = '010-4444-4444',
    CEMAIL = 'QER@QER.COM',
    CADDRESS = '남양주시',
    CGENDER = 'M',
    CBIRTH = '1992-02-11'
    WHERE CID = 'AAA';

-- 로그인 확인
SELECT * FROM CUSTOMER WHERE CID = 'AAA' AND CPW = '111';

COMMIT;

select * from customer;






