
-- ex1. 사용자에게 부서번호 입력받아 정보 뿌리기
SELECT * FROM DEPT WHERE DEPTNO=30;

INSERT INTO DEPT VALUES(50, 'IT', 'SEOUL');
COMMIT;
SELECT * FROM DEPT;
DELETE FROM DEPT WHERE DNAME = 'IT';


-- EX2. 
SELECT * FROM DEPT WHERE DEPTNO=30;
    -- 해당부서번호 사원의 정보(사번, 이름, 급여, 상사명)
SELECT W.EMPNO, W.ENAME , W.SAL, M.ENAME MANAGER
    FROM EMP W, EMP M
    WHERE W.MGR = M.EMPNO AND W.DEPTNO = 30;
    
-- EX3.
SELECT * FROM DEPT WHERE DNAME = UPPER('SALES');

SELECT EMPNO, ENAME, SAL, GRADE FROM EMP E, SALGRADE, DEPT D
    WHERE E.DEPTNO = D.DEPTNO AND DNAME = UPPER('SALES') AND SAL BETWEEN LOSAL AND HISAL ; 

SELECT EMPNO, ENAME, SAL, GRADE
    FROM EMP, SALGRADE
    WHERE SAL BETWEEN LOSAL AND HISAL AND
    DEPTNO = (SELECT DEPTNO FROM DEPT WHERE DNAME = UPPER('SALES'));





             